# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ResponseMsg(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tag=None, ts=None, data=None):  # noqa: E501
        """ResponseMsg - a model defined in OpenAPI

        :param tag: The tag of this ResponseMsg.  # noqa: E501
        :type tag: str
        :param ts: The ts of this ResponseMsg.  # noqa: E501
        :type ts: int
        :param data: The data of this ResponseMsg.  # noqa: E501
        :type data: object
        """
        self.openapi_types = {
            'tag': str,
            'ts': int,
            'data': object
        }

        self.attribute_map = {
            'tag': 'tag',
            'ts': 'ts',
            'data': 'data'
        }

        self._tag = tag
        self._ts = ts
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseMsg':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The response_msg of this ResponseMsg.  # noqa: E501
        :rtype: ResponseMsg
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tag(self):
        """Gets the tag of this ResponseMsg.

        Message type of payload  # noqa: E501

        :return: The tag of this ResponseMsg.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ResponseMsg.

        Message type of payload  # noqa: E501

        :param tag: The tag of this ResponseMsg.
        :type tag: str
        """

        self._tag = tag

    @property
    def ts(self):
        """Gets the ts of this ResponseMsg.

        Timestamp of message generation  # noqa: E501

        :return: The ts of this ResponseMsg.
        :rtype: int
        """
        return self._ts

    @ts.setter
    def ts(self, ts):
        """Sets the ts of this ResponseMsg.

        Timestamp of message generation  # noqa: E501

        :param ts: The ts of this ResponseMsg.
        :type ts: int
        """

        self._ts = ts

    @property
    def data(self):
        """Gets the data of this ResponseMsg.

        Payload (in json format)  # noqa: E501

        :return: The data of this ResponseMsg.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ResponseMsg.

        Payload (in json format)  # noqa: E501

        :param data: The data of this ResponseMsg.
        :type data: object
        """

        self._data = data
